blueprints/candidates.py
from flask import Blueprint, render_template, redirect, request, url_for
from sqlalchemy import select

from datamodels import VacancyResponses, Vacancies, Companies, Users, Resumes, Workplaces, t_resumeWorkplaces
from flask_login import current_user
from lib import db, utility

import sqlalchemy as sa

candidates = Blueprint('candidates', __name__, template_folder='templates', url_prefix='/candidates')


@candidates.route('/')
def candidatesPageRoute():
  session = db.getDBSession()

  if not current_user.is_authenticated:
    return redirect("/login")

  userId = current_user.get_id()

  user = session.scalar(
    sa.select(Users).where(Users.id == userId))

  if user.roleId != 2:
    return redirect("/")

  responses_data = session.execute(
    sa.select(Resumes, VacancyResponses, Vacancies, Users)
    .join(Users, Resumes.userId == Users.id)
    .join(VacancyResponses, VacancyResponses.userId == Users.id)
    .join(Vacancies, VacancyResponses.vacancyId == Vacancies.id)
    .join(Companies, Vacancies.companyId == Companies.id)
    .where(Companies.userId == current_user.id)
    .order_by(VacancyResponses.created.desc())
  ).all()

  result = []
  for resume, response, vacancy, user in responses_data:
    workplaces = session.execute(
      sa.select(Workplaces)
      .join(t_resumeWorkplaces, Workplaces.id == t_resumeWorkplaces.c.workplaceId)
      .where(t_resumeWorkplaces.c.resumeId == resume.id)
      .order_by(
        Workplaces.endYear.is_(None).desc(),
        Workplaces.endYear.desc(),
        Workplaces.beginYear.desc()
      )
    ).scalars().all()

    result.append({
      'resume': resume,
      'response': response,
      'vacancy': vacancy,
      'user': user,
      'workplaces': workplaces
    })

  return render_template('candidates.html', responses=result, format_date=utility.format_date, utility=utility)


@candidates.route('/update-response-status', methods=['POST'])
def cupdate_response_status():
  if not current_user.is_authenticated:
    return redirect("/login")

  vacancy_id = request.form.get('vacancy_id')
  user_id = request.form.get('user_id')
  new_status = request.form.get('new_status')

  session = db.getDBSession()
  response = session.execute(select(VacancyResponses)
        .where(VacancyResponses.vacancyId == vacancy_id)
        .where(VacancyResponses.userId == user_id)).scalar_one_or_none()

  if not response:
    return redirect(url_for('candidates.candidatesPageRoute'))

  try:
    response.status = int(new_status)
    session.commit()
  except Exception as e:
    session.rollback()
    print(f'Ошибка: {str(e)}', 'error')
  finally:
    session.close()

  return redirect(url_for('candidates.candidatesPageRoute'))

blueprints/companies.py
from flask import Blueprint, render_template, request, current_app, redirect
from sqlalchemy import select, asc
from flask_login import current_user
from werkzeug.datastructures import MultiDict

from forms import CompanyMainForm

from datamodels import Users, Vacancies, Companies, Contacts, ContactTypes, t_companyContacts
from lib import db
from lib import searchFunc

import sqlalchemy as sa
import sys, datetime, urllib, re

sys.path.append('../blocks')

from blocks import numerator

itemsPerPage = 20

companies = Blueprint('companies', __name__, template_folder='templates', url_prefix='/companies')


@companies.route('/')
def companiesPageRoute():
  session = db.getDBSession()

  sortBy = request.args.get('sort', 'date')
  sortOrder = request.args.get('order', 'desc')
  searchText = request.args.get('search', '').strip()

  pageURLArgName = 'page'
  page = int(request.args.get(pageURLArgName, 1))

  if (page < 1):
    page = 1

  limit = itemsPerPage
  offset = (page - 1) * itemsPerPage

  searchCompaniesCount = searchFunc.doSearch('companies', 'title', searchText, offset, limit, sortOrder, sortBy, True)
  searchResult = searchFunc.doSearch('companies', 'title', searchText, offset, limit, sortOrder, sortBy)

  for searchResultItem in searchResult:
    if (('company' in searchResultItem) and isinstance(searchResultItem['company'], dict)):
      if ('created' in searchResultItem['company']):
        searchResultItem['company']['created'] = datetime.datetime.strptime(searchResultItem['company']['created'],
                                                                            '%Y.%m.%d %H:%M:%S')
      if ('description' in searchResultItem['company']):
        searchResultItem['company']['description'] = re.sub(r"<[^>]*?>", ' ',
                                                            str(searchResultItem['company']['description']))

  requestArgs = request.args.to_dict()

  if (pageURLArgName in requestArgs):
    del requestArgs[pageURLArgName]

  requestArgs['page'] = ''

  paginationURLPrefix = urllib.parse.urlencode(requestArgs)
  paginationBaseURL = request.url_rule.rule

  if (paginationBaseURL.endswith('/')):
    paginationBaseURL = paginationBaseURL[:-1]

  pagesTotal = int(searchCompaniesCount / itemsPerPage)

  if (searchCompaniesCount % itemsPerPage > 0):
    pagesTotal += 1

  pageNumeratorHTML = numerator.NumeratorBlock.create({
    'currentPage': page,
    'pagesTotal': pagesTotal,
    'baseURL': paginationBaseURL,  ## request.url_rule.rule,
    'pageNumberPrefix': f"?{paginationURLPrefix}"
  })

  return render_template('companies.html', companies=searchResult, total_companies=searchCompaniesCount,
                         current_sort=sortBy, current_order=sortOrder, page_numerator=pageNumeratorHTML,
                         search_text=searchText)


@companies.route('/<int:companyId>')
def companyPageRoute(companyId):
  if companyId < 1:
    return redirect("404.html")

  session = db.getDBSession()

  company = session.scalar(
    sa.select(Companies).where(Companies.id == companyId)
  )

  if not company:
    return redirect("404.html")

  sortBy = request.args.get('sort', 'date')
  sortOrder = request.args.get('order', 'desc')
  searchText = request.args.get('search', '').strip()

  pageURLArgName = 'page'
  page = int(request.args.get(pageURLArgName, 1))

  if (page < 1):
    page = 1

  limit = itemsPerPage
  offset = (page - 1) * itemsPerPage

  searchVacanciesCount = searchFunc.doSearch('companyVacancies', companyId, searchText, offset, limit, sortOrder,
                                             sortBy, True)
  searchResult = searchFunc.doSearch('companyVacancies', companyId, searchText, offset, limit, sortOrder, sortBy)

  for searchResultItem in searchResult:
    if (('vacancy' in searchResultItem) and isinstance(searchResultItem['vacancy'], dict)):
      if ('created' in searchResultItem['vacancy']):
        searchResultItem['vacancy']['created'] = datetime.datetime.strptime(searchResultItem['vacancy']['created'],
                                                                            '%Y.%m.%d %H:%M:%S')
      if ('description' in searchResultItem['vacancy']):
        searchResultItem['vacancy']['description'] = re.sub(r"<[^>]*?>", ' ',
                                                            str(searchResultItem['vacancy']['description']))

  requestArgs = request.args.to_dict()

  if (pageURLArgName in requestArgs):
    del requestArgs[pageURLArgName]

  requestArgs['page'] = ''

  paginationURLPrefix = urllib.parse.urlencode(requestArgs)
  paginationBaseURL = f"/companies/{companyId}"

  if (paginationBaseURL.endswith('/')):
    paginationBaseURL = paginationBaseURL[:-1]

  pagesTotal = int(searchVacanciesCount / itemsPerPage)

  if (searchVacanciesCount % itemsPerPage > 0):
    pagesTotal += 1

  pageNumeratorHTML = numerator.NumeratorBlock.create({
    'currentPage': page,
    'pagesTotal': pagesTotal,
    'baseURL': paginationBaseURL,
    'pageNumberPrefix': f"?{paginationURLPrefix}"
  })

  query = (select(
    (Companies.id).label('companyId'),
    (Companies.userId).label('companyUserId'),
    (Companies.created).label('companyCreated'),
    (Companies.title).label('companyTitle'),
    (Companies.description).label('companyDescription'),
    (Companies.website).label('companyWebsite'),
    (Companies.industry).label('companyIndustry'),
    (Companies.foundationYear).label('companyFoundationYear'),
    (Companies.employeesCount).label('companyEmployeesCount')
  )
           .where(Companies.id == companyId)
           .limit(1)
           )

  companyResult = {}

  result = session.execute(query)
  resultItem = result.one()

  if (resultItem):
    contacts = {}

    contactsQuery = (select(
      (Contacts.value).label('contactValue'),
      (ContactTypes.title).label('contactTypeTitle')
    )
                     .where(t_companyContacts.c.companyId == companyId)
                     .where(t_companyContacts.c.contactId == Contacts.id)
                     .where(Contacts.contactTypeId == ContactTypes.id)
                     .order_by(asc(Contacts.contactTypeId))
                     .order_by(asc(Contacts.id))
                     )

    contactsResult = session.execute(contactsQuery)

    for contactsResultItem in contactsResult:
      if (contactsResultItem.contactTypeTitle not in contacts):
        contacts[contactsResultItem.contactTypeTitle] = []

      contacts[contactsResultItem.contactTypeTitle].append(contactsResultItem.contactValue)

    companyResult = {
      'company': {
        'id': resultItem.companyId,
        'userId': resultItem.companyUserId,
        'created': datetime.datetime.strptime((resultItem.companyCreated).strftime('%Y.%m.%d %H:%M:%S'),
                                              '%Y.%m.%d %H:%M:%S'),
        'title': resultItem.companyTitle,
        'description': (str(resultItem.companyDescription) if (resultItem.companyDescription is not None) else None),
        'website': resultItem.companyWebsite,
        'industry': resultItem.companyIndustry,
        'foundationYear': resultItem.companyFoundationYear,
        'employeesCount': resultItem.companyEmployeesCount,
        'contacts': contacts
      }
    }

  return render_template('company.html', companyResult=companyResult, vacancies=searchResult,
                         total_vacancies=searchVacanciesCount,
                         current_sort=sortBy, current_order=sortOrder, page_numerator=pageNumeratorHTML,
                         search_text=searchText)


@companies.route('/create', methods=['GET', 'POST'])
def createCompanyPageRoute():
  session = db.getDBSession()
  if not current_user.is_authenticated:
    return redirect("/login")

  userId = current_user.get_id()

  user = session.scalar(
    sa.select(Users).where(Users.id == userId))

  if user.roleId != 2:
    return redirect("/")

  form = CompanyMainForm()

  if form.validate_on_submit():
    created = datetime.datetime.now()
    title = form.title.data
    description = form.description.data
    website = form.website.data
    foundationYear = form.found.data
    employeesCount = form.employees.data

    company = Companies(userId=userId,
                        created=created,
                        title=title,
                        description=description,
                        website=website,
                        foundationYear=foundationYear,
                        employeesCount=employeesCount,
                        )

    email = Contacts(
      contactTypeId=2,
      value=form.email.data
    )

    address = Contacts(
      contactTypeId=1,
      value=form.adress.data
    )

    tel = Contacts(
      contactTypeId=4,
      value=form.tel.data
    )

    try:
      session.add(company)
      session.add(email)
      session.add(address)
      session.add(tel)
      session.flush()

      session.execute(
        t_companyContacts.insert().values([
          {'companyId': company.id, 'contactId': email.id},
          {'companyId': company.id, 'contactId': address.id},
          {'companyId': company.id, 'contactId': tel.id}
        ])
      )

      session.commit()
    except Exception as e:
      session.rollback()
      return f"{e}"
    return redirect("/account_page")

  return render_template('create_company.html', form=form)


@companies.route('/edit/<int:companyId>', methods=['GET', 'POST'])
def editCompanyPageRoute(companyId):
  session = db.getDBSession()

  if not current_user.is_authenticated:
    return redirect("/login")

  company = session.scalar(
    sa.select(Companies).where(Companies.id == companyId))

  if not company or company.userId != int(current_user.get_id()):
    return redirect("404.html")

  contacts = session.scalars(select(Contacts)
                             .join(t_companyContacts, Contacts.id == t_companyContacts.c.contactId)
                             .where(t_companyContacts.c.companyId == companyId)).all()

  form = CompanyMainForm()

blueprints/responses.py
import random

from flask import Blueprint, render_template, redirect, request, url_for
from datamodels import VacancyResponses, Vacancies, Companies, Users
from flask_login import current_user
from lib import db, utility

import sqlalchemy as sa

import datetime

responses = Blueprint('responses', __name__, template_folder='templates', url_prefix='/responses')


@responses.route('/')
def responsesPageRoute():
  session = db.getDBSession()

  if not current_user.is_authenticated:
    return redirect("/login")

  userId = current_user.get_id()

  user = session.scalar(
    sa.select(Users).where(Users.id == userId))

  if user.roleId != 3:
    return redirect("/")

  responses_data = session.execute(
    sa.select(VacancyResponses, Vacancies, Companies)
    .join(Vacancies, VacancyResponses.vacancyId == Vacancies.id)
    .join(Companies, Vacancies.companyId == Companies.id)
    .where(VacancyResponses.userId == int(current_user.get_id()))
    .order_by(VacancyResponses.created.desc())
  ).all()

  return render_template('responses.html', responses=responses_data, format_date=utility.format_date)


def generate_responses(session):
  try:
    vacancy_ids = [56, 757, 973, 1402, 1501]
    user_ids = list(range(1, 1019))

    for vacancy_id in vacancy_ids:
      selected_users = random.sample(user_ids, 30)
      selected_users.append(1021)
      for user_id in selected_users:
        response = VacancyResponses(
          vacancyId=vacancy_id,
          userId=user_id,
          created=datetime.datetime.now(),
        )

        session.add(response)

    session.commit()

  except Exception as e:
    session.rollback()
    print(f"Ошибка: {e}")


@responses.route('/update-response-status', methods=['POST'])
def update_response_status():
    if not current_user.is_authenticated:
        return redirect("/login")

    vacancy_id = request.form.get('vacancy_id')
    user_id = request.form.get('user_id')
    new_status = request.form.get('new_status')

    if int(user_id) != int(current_user.get_id()):
        return redirect(url_for('responses.responsesPageRoute'))

    session = db.getDBSession()
    try:
        session.execute(
            sa.update(VacancyResponses)
            .where(VacancyResponses.vacancyId == vacancy_id)
            .where(VacancyResponses.userId == user_id)
            .values(status=new_status)
        )
        session.commit()
    except Exception as e:
        session.rollback()
        print(f'Ошибка: {str(e)}', 'error')
    finally:
        session.close()

    return redirect(url_for('responses.responsesPageRoute'))

blueprints/salaries.py
from flask import Blueprint, render_template, request, current_app, redirect
from sqlalchemy import select, text, join, desc, asc
from flask_login import current_user

from lib import db
from lib import searchFunc

import sys, datetime, urllib, re

sys.path.append('../blocks')

from blocks import numerator


itemsPerPage = 20

salaries = Blueprint('salaries', __name__, template_folder='templates', url_prefix='/salaries')


@salaries.route('/')
def salariesPageRoute():
  session = db.getDBSession()

  pageURLArgName = 'page'
  page = int(request.args.get(pageURLArgName, 1))

  if (page < 1):
    page = 1

  limit = itemsPerPage
  offset = (page - 1) * itemsPerPage

  searchVacanciesCount = searchFunc.doSearch('topSalaryVacancies', '', '', offset, limit, '', '', True)
  searchResult = searchFunc.doSearch('topSalaryVacancies', '', '', offset, limit, '', '')

  for searchResultItem in searchResult:
    if (('vacancy' in searchResultItem) and isinstance(searchResultItem['vacancy'], dict)):
      if ('created' in searchResultItem['vacancy']):
        searchResultItem['vacancy']['created'] = datetime.datetime.strptime(searchResultItem['vacancy']['created'], '%Y.%m.%d %H:%M:%S')
      if ('description' in searchResultItem['vacancy']):
        searchResultItem['vacancy']['description'] = re.sub(r"<[^>]*?>", ' ', str(searchResultItem['vacancy']['description']))

  requestArgs = request.args.to_dict()

  if (pageURLArgName in requestArgs):
    del requestArgs[pageURLArgName]

  requestArgs['page'] = ''

  paginationURLPrefix = urllib.parse.urlencode(requestArgs)
  paginationBaseURL = request.url_rule.rule

  if (paginationBaseURL.endswith('/')):
    paginationBaseURL = paginationBaseURL[:-1]

  pagesTotal = 5

  pageNumeratorHTML = numerator.NumeratorBlock.create({
    'currentPage': page,
    'pagesTotal': pagesTotal,
    'baseURL': paginationBaseURL,
    'pageNumberPrefix': f"?{paginationURLPrefix}"
  })

  return render_template('salaries.html', vacancies = searchResult, page_numerator = pageNumeratorHTML)

templates/blankbase.html
<!DOCTYPE html>
<html itemscope="" itemtype="https://schema.org/WebSite" lang="en" dir="ltr">
<head>
  <title>{% block title %} {% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="Content-Language" content="en" />
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1" />
  <link type="image/x-icon" rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}" />
  <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='styles/blocks/topMenu/main.css') }}" />
  <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='styles/fonts/Roboto.css') }}" />
  <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='styles/themes/default.css') }}" />
  <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='styles/main.css') }}" />
  <script src="/scripts/blocks/topMenu/main.js" type="text/javascript"></script>
  <script src="/scripts/main.js" type="text/javascript"></script>
</head>
<body style="background: white">
{% block content %}

{% endblock %}
</body>
</html>

templates/companies.html
{% extends 'base.html' %}

{% block title %} Компании {% endblock %}

{% block content %}
<div class="contentWrap sectionBox">
  <div>
    <div class="resultsHeaderBlock">
      <div class="resultsCountBlock">
        <h2>Найдено {{ total_companies }} компаний</h2>
      </div>
      <div class="searchBlock">
        <form method="get" style="display: flex;">
          <input name="search" placeholder="" value="{{ search_text }}" />
          <button type="submit">Искать</button>
        </form>
      </div>
      <div class="clear"></div>
    </div>
    <div class="vacanciesMainBlock">
      <div class="vacanciesListBlock">
        {% for companyResult in companies %}
        <a href="{{ url_for('companies.companyPageRoute', companyId = companyResult['company']['id']) }}">
          <div class="vacancyCard">
            <div class="vacancyCardContent">
              <span class="vacancyCardTitle">{{ companyResult['company']['title'] }}</span>
              {% if companyResult['company'] %}
              <hr noshade size="1" style="margin: 0;">
              <div style="display: flex; gap: 8px;">
                <span style="flex-shrink: 0; width: 15%;">{{ companyResult['company']['title'] }}</span>
                <div style="display: flex; flex-flow: column;">
                  <span class="vacancyCardDescription"> {{ companyResult['company']['description'] }}</span>
                </div>
              </div>
              {% endif %}
            </div>
          </div>
        </a>
        {% endfor %}
      </div>
    </div>
    <br />
    {% autoescape false %}
    <div>{{ page_numerator }}</div>
    {% endautoescape %}
  </div>
</div>
<script>
document.addEventListener('DOMContentLoaded', function() {
  const toggleBtn = document.getElementById('sorting-toggle');
  const dropdown = document.getElementById('sorting-dropdown');

  // Переключение видимости dropdown
  toggleBtn.addEventListener('click', function(e) {
    e.stopPropagation();
    dropdown.classList.toggle('show');
    toggleBtn.querySelector('.dropdown-icon').style.transform =
      dropdown.classList.contains('show') ? 'rotate(180deg)' : 'rotate(0)';
  });

  document.addEventListener('click', function() {
    dropdown.classList.remove('show');
    toggleBtn.querySelector('.dropdown-icon').style.transform = 'rotate(0)';
  });
});

document.addEventListener('DOMContentLoaded', function() {
  const sortOrderBtn = document.getElementById('sort-order-btn');

  // Получаем текущий порядок из URL
  const urlParams = new URLSearchParams(window.location.search);
  let isAscending = urlParams.get('order') === 'asc';

  // Устанавливаем начальное состояние
  if (isAscending) {
    sortOrderBtn.classList.add('asc');
  }

  sortOrderBtn.addEventListener('click', function(e) {
    e.preventDefault();
    isAscending = !isAscending;

    // Переключаем класс
    this.classList.toggle('asc', isAscending);

    // Обновляем URL
    updateSortOrder(isAscending);
  });

  function updateSortOrder(ascending) {
    const currentUrl = new URL(window.location.href);
    currentUrl.searchParams.set('order', ascending ? 'asc' : 'desc');
    window.location.href = currentUrl.toString();
  }
});
</script>

{% endblock %}

templates/login.html
{% extends 'blankbase.html' %}

{% block content %}
<div class="registerWrap registerBox">
    <div class="formBox">
        <a class="back-button" href="/">Назад</a>
      <h1>Вход</h1>
        {% with messages = get_flashed_messages() %}
          {% if messages %}
            <ul class="regErrorMessage">
              {% for message in messages %}
                <li style="color: red;">{{ message }}</li>
              {% endfor %}
            </ul>
          {% endif %}
        {% endwith %}
        <form action="" method="post" novalidate>
            {{ form.hidden_tag() }}
            <p class="fieldsMargin">
              {{ form.email(size=32, class="form-field") }}<br>
              {% for error in form.email.errors %}
                <span style="color: red;">[{{ error }}]</span>
              {% endfor %}
            </p>
            <p class="fieldsMargin">
              {{ form.password(size=32, class="form-field") }}<br>
              {% for error in form.password.errors %}
                <span style="color: red;">[{{ error }}]</span>
              {% endfor %}
            </p>
            <p>{{ form.submit(class="submit-button") }}</p>
        </form>
        <span>Нет аккаунта? <a href="/register">Зарегестрироваться</a></span>
    </div>
</div>
{% endblock %}

templates/my_vacancies.html
{% extends 'base.html' %}

{% block title %} Мои вакансии {% endblock %}

{% block content %}
<div class="contentWrap sectionBox">
  <div>
    <div style="display: flex; justify-content: space-between; align-items: center;">
          <h2 style="font-size: 1.7rem;">Мои вакансии</h2>
          {% if company %}
          <a class="redirect-button" href="{{ url_for('vacancies.createVacancyPageRoute') }}">Создать вакансию</a>
          {% else %}
          <a class="redirect-button" href="{{ url_for('companies.createCompanyPageRoute') }}">Создать компанию</a>
          {% endif %}
    </div>
    {% if vacancies %}
    <div class="resumesMainBlock">
      <div class="resumesListBlock">
        {% for vacancyResult in vacancies %}
          <div class="resumeCard" style="cursor: default;">
            <div class="resumeCardContent">
              <a href="{{ url_for('vacancies.vacancyPageRoute', vacancyId = vacancyResult['vacancy']['id']) }}">
              <span class="resumeCardTitle">{{ vacancyResult['vacancy']['title'] }}</span>
                        </a>
              <span class="resumeCardTitle" style="font-size: 1rem;">Обновлено {{ utility.format_date(vacancyResult['vacancy']['created']) }}</span>
              <div style="display: flex; gap: 15px;">
              <a class="edit-button" href="{{ url_for('vacancies.editVacancyPageRoute', vacancyId = vacancyResult['vacancy']['id']) }}">Редактировать</a>
                <form method="POST" action="{{ url_for('vacancies.delete_vacancy', vacancyId=vacancyResult['vacancy']['id']) }}"
                      onsubmit="return confirm('Вы уверены, что хотите удалить эту вакансию?');"
                      style="display: inline;">
                  <input type="hidden"/>
                  <button type="submit" class="edit-button">Удалить</button>
                </form>
                </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
      <br />
    {% autoescape false %}
    <div>{{ page_numerator }}</div>
    {% endautoescape %}
    {% endif %}
  </div>
</div>

{% endblock %}

templates/responses.html
{% extends 'base.html' %}

{% block content %}
<div class="contentWrap sectionBox">
    <div class="responsesMainText">
        <span>Ваши отклики</span>
    </div>

    {% if responses %}
    <div class="responsesMainBlock">
        <div class="tabs">
            <button class="redirect-button tab-button active" data-tab="all">Все</button>
            <button class="redirect-button tab-button" data-tab="invitation">Приглашение</button>
            <button class="redirect-button tab-button" data-tab="rejection">Отказ</button>
            <button class="redirect-button tab-button" data-tab="pending">На рассмотрении</button>
            <button class="redirect-button tab-button" data-tab="archived">Удаленные</button>
        </div>
        <div class="tab-content">
        {% for response, vacancy, company in responses %}
                <div class="responsesCard" data-tab="all {% if response.status == 1 %}invitation{% elif response.status == 2 %}rejection{% elif response.status == 3 %}archived{% else %}pending{% endif %}">
                        <div class="responsesCardContent">
                            <div class="responsesTitle">
                                <a class="responsesTitleLink" href="/vacancies/{{vacancy.id}}">
                                    <span>{{ vacancy.title }}</span>
                                </a>
                                <span class="status-badge">
                                    {% if response.status == 1 %}
                                      приглашение
                                    {% elif response.status == 2 %}
                                      отказ
                                    {% elif response.status == 3 %}
                                      удалено
                                    {% else %}
                                      на рассмотрении
                                    {% endif %}
                                </span>
                            </div>
                            <span>{{ company.title }}</span>
                            <span>{{ format_date(response.created) }}</span>

                            <div class="response-actions">
                                <form method="POST" action="{{ url_for('responses.update_response_status') }}" class="d-inline">
                                <input type="hidden" name="vacancy_id" value="{{ response.vacancyId }}">
                                <input type="hidden" name="user_id" value="{{ response.userId }}">
                                <input type="hidden" name="new_status" value="{{ 3 if response.status != 3 else 0 }}">

                                <button type="submit" class="responses-delete-button btn {% if response.status == 3 %}btn-success{% else %}btn-danger{% endif %}">
                                  {% if response.status == 3 %}
                                    Восстановить
                                  {% else %}
                                    Удалить
                                  {% endif %}
                                </button>
                              </form>
                          </div>
                        </div>
                    </div>
        {% endfor %}
        </div>
    </div>
    {% else %}
    <div class="responsesEmptyBlock">
        <span>Здесь будут находиться ваши отклики. <br> Откликайтесь на вакансии, так больше шансов найти работу!</span>
        <a href="/vacancies" class="redirect-button">Искать вакансии</a>
    </div>
    {% endif %}
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
  const tabButtons = document.querySelectorAll('.tab-button');

  tabButtons.forEach(button => {
    button.addEventListener('click', function() {
      // Удаляем активный класс у всех кнопок
      tabButtons.forEach(btn => btn.classList.remove('active'));
      // Добавляем активный класс текущей кнопке
      this.classList.add('active');

      const tabName = this.getAttribute('data-tab');
      const cards = document.querySelectorAll('.responsesCard');

      cards.forEach(card => {
        if (tabName === 'all') {
          card.style.display = 'block';
        } else {
          card.style.display = card.getAttribute('data-tab').includes(tabName) ? 'block' : 'none';
        }
      });
    });
  });
});
</script>

{% endblock %}